### ISSUE TITLE
HW grading

### ISSUE THREAD

**Issue by CJHKGZZ** [jtr13/1201#18]
If I believe my PSET was correct but was given an incorrect grade, can we get a regrade with adequate proof?

**Comment by jtr13** [comment]
Hi, Please see the syllabus https://github.com/jtr13/1201/blob/master/Syllabus.md for TA contact info and send the appropriate TA an email.  (By the way, this page is for suggestions for adding to the supplemental resource... communication on other topics should be done by email. Thanks!)
