### ISSUE TITLE
Adding ranges to Functions and overlaying plots in R

### ISSUE THREAD

**Issue by SamJonesColumbia21** [jtr13/1201#21]

**Comment by SamJonesColumbia21** [comment]
I cannot work out how to add ranges to my functions in R so that I can create pdfs - this is what I have so far: 

y <- c(0:5)
x <- c(5:10)
a <- function(y) y/25
b <- function(x) 2/5 - x/25 
plot(a, xlim = c(0,5))
plot(b, xlim = c(5,10))

But this sort of limits the usage of the function as a whole since the variable has to be defined rather than the function.

Also, it would be great to present the function in a single graph - do you know how to combine plots?

Thanks!

**Comment by jtr13** [comment]
I'm really not clear on what you're trying to do.

**Comment by SamJonesColumbia21** [comment]
I'm trying to do section 4.1 question 8a and trying to plot the pdf for the question. 

Since I can't add ranges to the variables in the function (the first bit to my q), I have to plot the various parts of the function in two separate graphs (the second part to my q).

1) Is there a way to add continuous ranges to functions

2) if not, how can you make two plots into one plot

**Comment by SamJonesColumbia21** [comment]
<img width="623" alt="screenshot 2019-02-26 at 18 07 35" src="https://user-images.githubusercontent.com/47230537/53453232-8c953100-39f1-11e9-9376-4e509a11e604.png">

**Comment by jtr13** [comment]
Got it.  We generally plot data not functions. I think this is what you want:
```
plot(y, a(y), type = "l", xlim = c(0, 10))
lines(x, b(x))
```

**Comment by SamJonesColumbia21** [comment]
Thank you! Worked perfectly!

**Comment by jtr13** [comment]
This cheatsheet might be helpful: https://github.com/jtr13/codehelp/blob/master/BaseGraphicsCheatsheet.pdf
